name: Run Python Scripts Every 4 Hours

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # Раскомментировано: Запуск каждые 4 часа

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    # Проверяем репозиторий с кодом
    - name: Checkout code
      uses: actions/checkout@v3

    # Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.0'  # Укажи нужную версию Python

    # Устанавливаем зависимости (если есть файл requirements.txt)
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install selenium  # Устанавливаем selenium

    # Устанавливаем Chrome
    - name: Install Chrome
      run: sudo apt-get install -y google-chrome-stable

    # Устанавливаем ChromeDriver
    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

    # Запуск первого Python скрипта с Selenium
    - name: Run first Python script
      run: python birge.py
      env:
        EMAIL_BIRGE: ${{ secrets.EMAIL_BIRGE }}
        PASS_BIRGE: ${{ secrets.PASS_BIRGE }}

      # Дополнительные аргументы для headless режима и избегания проблем с правами доступа
      # Убедитесь, что они добавлены в Python код:
      # options.add_argument("--no-sandbox")
      # options.add_argument("--disable-dev-shm-usage")

    # # Запуск второго Python скрипта
    # - name: Run second Python script
    #   run: python script2.py
