name: Run Python Scripts and Save Screenshots

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"  # Запуск каждые 4 часа

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    # Проверяем репозиторий с кодом
    - name: Checkout code
      uses: actions/checkout@v3

    # Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.0'

    # Запуск Python скрипта с Selenium
    - name: Run Python script
      run: python birge_up.py

